### ISSUE TITLE
Not able to flash picoW using picoprobe

### ISSUE THREAD

**Issue by Shikamru** [raspberrypi/picoprobe#110]
Hi team,
             I am using picoW board and c/c++ sdk on windows environment. I recently bought the picoprobe to flash and debug the picoW. However not able to to anything on this. I am referring the below link to flash and debug the picoW. Here is the link `https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html` . both gdb and openocd are up and verified the connections also still no luck. am attaching the logs here for reference. 
` PS C:\Users\Documents\Pico-v1.5.1\pico-examples\build\pico_w\wifi\blink> openocd.exe -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program picow_blink.elf verify reset exit"
Open On-Chip Debugger 0.11.0-g8e3c38f78 (2023-02-28-14:54)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
Info : Hardware thread awareness created
Info : Hardware thread awareness created
Info : RP2040 Flash Bank Command
adapter speed: 5000 kHz

Info : Using CMSIS-DAPv2 interface with VID:PID=0x2e8a:0x000c, serial=E6616407E3570E29
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 2.0.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 0 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 5000 kHz
Info : SWD DPIDR 0x0bc12477
Info : SWD DLPIDR 0x00000001
Info : SWD DPIDR 0x0bc12477
Info : SWD DLPIDR 0x10000001
Info : rp2040.core0: hardware has 4 breakpoints, 2 watchpoints
Info : rp2040.core1: hardware has 4 breakpoints, 2 watchpoints
Info : starting gdb server for rp2040.core0 on 3333
Info : Listening on port 3333 for gdb connections
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
target halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
** Programming Started **
Warn : no flash bank found for address 0x10000000
Warn : no flash bank found for address 0x10041588
** Programming Finished **
** Verify Started **
target halted due to debug-request, current mode: Thread
xPSR: 0x61000000 pc: 0x1000132c msp: 0x20041fb0
Error: checksum mismatch - attempting binary compare
** Verify Failed **
shutdown command invoked`

note->  I even  Upgraded the picoprobe firmware to the latest version from this link [https://github.com/raspberrypi/picoprobe/releases](url) . after this it's is not working as expected. kindly guide me here . Just for sake of curiosity **Does picoprobe support picoW ?**

Regards,
Shikamaru

**Comment by peterharperuk** [comment]
I use picoprobe to debug pico w. I don't use Windows however

**Comment by peterharperuk** [comment]
Did you use this? https://github.com/raspberrypi/pico-setup-windows
I just tried it and it seemed to work to program picow_blink on a pico w

**Comment by P33M** [comment]
You have established a debug session, so there's nothing in this repo that can change to fix it.

**Comment by Shikamru** [comment]
> Did you use this? https://github.com/raspberrypi/pico-setup-windows I just tried it and it seemed to work to program picow_blink on a pico w

Yes I installed from above reference only.

**Comment by peterharperuk** [comment]
Please check you are using the right version of openocd It appears to be a bit different to mine?

```
`$ openocd.exe -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program picow_blink.elf verify reset exit"
Open On-Chip Debugger 0.12.0-g4257276 (2023-01-27-10:19)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : Hardware thread awareness created
Info : Hardware thread awareness created
adapter speed: 5000 kHz

Info : Using CMSIS-DAPv2 interface with VID:PID=0x2e8a:0x000c, serial=E6609103C389542C
Info : CMSIS-DAP: SWD supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: Test domain timer supported
Info : CMSIS-DAP: FW Version = 2.0.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 0 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 5000 kHz
Info : SWD DPIDR 0x0bc12477, DLPIDR 0x00000001
Info : SWD DPIDR 0x0bc12477, DLPIDR 0x10000001
Info : [rp2040.core0] Cortex-M0+ r0p1 processor detected
Info : [rp2040.core0] target has 4 breakpoints, 2 watchpoints
Info : [rp2040.core1] Cortex-M0+ r0p1 processor detected
Info : [rp2040.core1] target has 4 breakpoints, 2 watchpoints
Info : starting gdb server for rp2040.core0 on 3333
Info : Listening on port 3333 for gdb connections
[rp2040.core0] halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
[rp2040.core1] halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
** Programming Started **
Info : Found flash device 'win w25q16jv' (ID 0x001540ef)
Info : RP2040 B0 Flash Probe: 2097152 bytes @0x10000000, in 32 sectors

Info : Padding image section 1 at 0x10040478 with 136 bytes (bank write end alignment)
Warn : Adding extra erase range, 0x10040500 .. 0x1004ffff
** Programming Finished **
** Verify Started **
** Verified OK **
** Resetting Target **
shutdown command invoked
```

I opened a clean msys terminal and created the following and it worked.

```
export PATH=$PATH:/c/Program\ Files/Raspberry\ Pi/Pico\ SDK\ v1.5.1/openocd/
export OPENOCD_SCRIPTS=/c/Program\ Files/Raspberry\ Pi/Pico\ SDK\ v1.5.1/openocd/scripts/
```

**Comment by Shikamru** [comment]
> Please check you are using the right version of openocd It appears to be a bit different to mine?
> 
> ```
> `$ openocd.exe -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program picow_blink.elf verify reset exit"
> Open On-Chip Debugger 0.12.0-g4257276 (2023-01-27-10:19)
> Licensed under GNU GPL v2
> For bug reports, read
>         http://openocd.org/doc/doxygen/bugs.html
> Info : Hardware thread awareness created
> Info : Hardware thread awareness created
> adapter speed: 5000 kHz
> 
> Info : Using CMSIS-DAPv2 interface with VID:PID=0x2e8a:0x000c, serial=E6609103C389542C
> Info : CMSIS-DAP: SWD supported
> Info : CMSIS-DAP: Atomic commands supported
> Info : CMSIS-DAP: Test domain timer supported
> Info : CMSIS-DAP: FW Version = 2.0.0
> Info : CMSIS-DAP: Interface Initialised (SWD)
> Info : SWCLK/TCK = 0 SWDIO/TMS = 0 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
> Info : CMSIS-DAP: Interface ready
> Info : clock speed 5000 kHz
> Info : SWD DPIDR 0x0bc12477, DLPIDR 0x00000001
> Info : SWD DPIDR 0x0bc12477, DLPIDR 0x10000001
> Info : [rp2040.core0] Cortex-M0+ r0p1 processor detected
> Info : [rp2040.core0] target has 4 breakpoints, 2 watchpoints
> Info : [rp2040.core1] Cortex-M0+ r0p1 processor detected
> Info : [rp2040.core1] target has 4 breakpoints, 2 watchpoints
> Info : starting gdb server for rp2040.core0 on 3333
> Info : Listening on port 3333 for gdb connections
> [rp2040.core0] halted due to debug-request, current mode: Thread
> xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
> [rp2040.core1] halted due to debug-request, current mode: Thread
> xPSR: 0xf1000000 pc: 0x000000ea msp: 0x20041f00
> ** Programming Started **
> Info : Found flash device 'win w25q16jv' (ID 0x001540ef)
> Info : RP2040 B0 Flash Probe: 2097152 bytes @0x10000000, in 32 sectors
> 
> Info : Padding image section 1 at 0x10040478 with 136 bytes (bank write end alignment)
> Warn : Adding extra erase range, 0x10040500 .. 0x1004ffff
> ** Programming Finished **
> ** Verify Started **
> ** Verified OK **
> ** Resetting Target **
> shutdown command invoked
> ```
> 
> I opened a clean msys terminal and created the following and it worked.
> 
> ```
> export PATH=$PATH:/c/Program\ Files/Raspberry\ Pi/Pico\ SDK\ v1.5.1/openocd/
> export OPENOCD_SCRIPTS=/c/Program\ Files/Raspberry\ Pi/Pico\ SDK\ v1.5.1/openocd/scripts/
> ```

May i know which version of openocd you are using. i will try these suggestion as well and update here.

**Comment by Shikamru** [comment]
> Hmm, I would like to know where you got that old version of openocd from

Sure , am sharing the link below [https://www.waveshare.com/wiki/Raspberry_Pi_Debug_Probe](url) . There is part of Openocd installation for windows. From there I took it

**Comment by lurch** [comment]
I think we'd always advise people to use the officially-supported (and updated) https://github.com/raspberrypi/pico-setup-windows rather than downloading binaries from 3rd-party websites which may be old and outdated.
