### ISSUE TITLE
Access pico's ram through swd pins using another pico

### ISSUE THREAD

**Issue by Friday8229** [raspberrypi/picoprobe#25]
Okay so I'm trying to write some data to a pi pico using another pico. I know i can use a custom bootloader to achieve this but i want to write a program to a fresh pico (that is not running anything) using another pico.
This can be achieved using openocd and a raspberry pi or another Pico as picoprobe but i don't want to have a Linux machine.
Basically i want to program a pi pico from another pico.

Any suggestions how should I proceed?
My goal is to somehow access the slave pico's ram through the swd pins so i can write data directly to it using the master Pico

Can the source code of the Pico probe be modified to achieve this ? If yes can you guide me on how should I start !?

**Comment by lurch** [comment]
This isn't something that we have time to provide support for ourselves. Your best best is to probably ask for guidance on the [forums](https://forums.raspberrypi.com/viewforum.php?f=143) ?
