### ISSUE TITLE
Allow combining with micropython running on core1

### ISSUE THREAD

**Issue by raveslave** [raspberrypi/picoprobe#36]
I plan to use picoprobe in a CI environment where I'd like to enable another CDC endpoint that talks to a custom application running on the second core of the pico.

Would there be interest in adding such thing? As a start just a micropython REPL would do, this could even run on the same core as picoprobe if that simplifies things

**Comment by aallan** [comment]
We're a small team, and it's unlikely there will be any effort available to work on this idea. We're obviously happy for you to do so, and will look at any PRs you upstream to see if they can be incorporated into the release verison.
