### ISSUE TITLE
Q: can this expose a gdbstub to usbserial on another device?

### ISSUE THREAD

**Issue by stsquad** [raspberrypi/picoprobe#4]
Looking at the code I can see you are wiggling the SWD pins but it's not entirely clear what connects over the tiny usb side? What I'm looking to do is use one pico to provide a gdbstub while debugging another pico over the SWD without having to go through the fiddle of setting up a Raspberry Pi with OpenOCD.

Any chance of a quick README for the repo to explain the topology of a picoprobe setup?

**Comment by aallan** [comment]
`picoprobe` is documented in Appendix A of "[Getting started with Raspberry Pi Pico](https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf)".
