### ISSUE TITLE
Add output indicating direction of SWDIO

### ISSUE THREAD

**Issue by diggit** [raspberrypi/picoprobe#57]
To be able to use picoprobe with digital isolators, information about SWDIO direction needs to be also available on isolated side (for tri-stating output).
I don't think this would bee too much effort to add and picoprobe would be more versatile.

**Comment by P33M** [comment]
I have a local patch for just such a thing, as we're using level-shifted outputs on a few internal development boards. Not quite public yet.

**Comment by P33M** [comment]
see https://github.com/raspberrypi/picoprobe/commit/964780b2b2d993bbf451b22c46f02f8853f08e6e and friends for just such an example.
