### ISSUE TITLE
building picoprobe failed

### ISSUE THREAD

**Issue by ZamanImranMS** [raspberrypi/picoprobe#58]
![image](https://user-images.githubusercontent.com/94702884/209520284-efce1eb5-24b0-4923-bfe6-266946d79e0b.png)
While building the picoprobe it fails. I don't know why but it seem that it have something issue with FreeRTOS.

**Comment by ZamanImranMS** [comment]
This issue is fixed by using these commands
` cd picoprobe
git submodule update --init
`

**Comment by lurch** [comment]
Yes, which it says in Appendix A of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf - perhaps you're looking at an old version of the PDF?
