### ISSUE TITLE
PicoProbe wont work, comes up as stuff other than interface 0 and 2 using the precompiled uf2 f 

### ISSUE THREAD

**Issue by FJay81** [raspberrypi/picoprobe#68]
![image](https://user-images.githubusercontent.com/82079632/220205660-5a23fa71-517d-4c93-bdaa-999b1e171f69.png)
![image](https://user-images.githubusercontent.com/82079632/220205789-fbb8bda1-f24a-4337-adc9-ab3fa958fb7c.png)
![image](https://user-images.githubusercontent.com/82079632/220205831-1e271ebc-0a50-4d7a-8c4c-d3dcc13a8470.png)
![image](https://user-images.githubusercontent.com/82079632/220205854-684b1e9d-409e-465e-a9f1-60ed731fbba0.png)

**Comment by P33M** [comment]
Whose instructions are you following?

The releases in this repo do not require Zadig.

**Comment by FJay81** [comment]
[Tutorial](https://www.digikey.co.uk/en/maker/projects/raspberry-pi-pico-and-rp2040-cc-part-2-debugging-with-vs-code/470abc7efb07432b82c95f6f67f184c0)
This one by digi key,
Can you use the pico for just uart without swd?

**Comment by aallan** [comment]
See Appendix A of "[Getting started with Raspberry Pi Pico](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf)" for the official tutorial.

**Comment by FJay81** [comment]
![image](https://user-images.githubusercontent.com/82079632/220365213-b06468a7-ec27-482d-9418-673fdbb3ea0a.jpeg)

So that will allow me to use the Pico like this thing?

**Comment by aallan** [comment]
> So that will allow me to use the Pico like this thing?

So that needs fixing! 🤷‍♂️

**Comment by FJay81** [comment]
i found something that does that now [The thingy](https://github.com/Noltari/pico-uart-bridge)

**Comment by lurch** [comment]
See also https://www.raspberrypi.com/news/raspberry-pi-debug-probe-a-plug-and-play-debug-kit-for-12

**Comment by lurch** [comment]
> So that will allow me to use the Pico like this thing?

Yes, you can use a Pico running PicoProbe as a USB-UART adaptor. The bit that "needs fixing" that @aallan is referring to is that the GND wire in that diagram is connected to the wrong hole on the breadboard.

**Comment by FJay81** [comment]
ive seen the probe thingy, it was out of stock when i went to buy it hence this

**Comment by aallan** [comment]
> ive seen the probe thingy, it was out of stock when i went to buy it hence this

Launched yesterday. Initial stocks at resellers were exhausted, but it'll be back in stock very soon. Plenty in channel.

**Comment by FJay81** [comment]
So I got it sorted but when I went to connect to a router of mine which I checked with a multimeter to figure which pins are what it didn’t work, I’m using putty and a compile version of Pico probe from here and cannot for the life of me get an output in putty, I’m connected to the serial port whic comes up as usb cdc com7 and connect to it as com7 and different bauderates, but no output on the console is there any way to get an output?

**Comment by lurch** [comment]
> when I went to connect to a router of mine

You won't be surprised to hear that that's not a use-case we can officially provide support for :wink:  You could try asking for help on the https://forums.raspberrypi.com/ ?

**Comment by FJay81** [comment]
Ok will do
