### ISSUE TITLE
Can not getting UART fucntion work as expected on PICO

### ISSUE THREAD

**Issue by peterpanstechland** [raspberrypi/picoprobe#70]
I am trying to use my Raspberry Pi PICO as a debugger with this project, however the UART function is only works in one direction in my case.

If i set the UART config in picoprobe_confg.h like this which utilizing UART1:
```
// UART config
#define PICOPROBE_UART_TX 4
#define PICOPROBE_UART_RX 5
#define PICOPROBE_UART_INTERFACE uart1
#define PICOPROBE_UART_BAUDRATE 115200

```

Only the TX pin is working which could send message to the second usb to uart device.

---

If i set the UART config in picoprobe_confg.h like this utilizing UART0:
```
// UART config
#define PICOPROBE_UART_TX 0
#define PICOPROBE_UART_RX 1
#define PICOPROBE_UART_INTERFACE uart0
#define PICOPROBE_UART_BAUDRATE 115200

```
Only the RX pin is working which could receive message from the second usb to uart device.

---

Then I put the UART0 configured firmware into the XIAO RP2040 and it act the same as Raspberry Pi PICO which only the RX pin works.

Please help me on this. I am waiting on the new Picoprobe and that's how I got into this. 

Thanks.

**Comment by P33M** [comment]
Questions such as these are best asked in our forum: https://forums.raspberrypi.com/viewforum.php?f=144
