### ISSUE TITLE
Error: Error connecting DP: cannot read IDR

### ISSUE THREAD

**Issue by crisgplj** [raspberrypi/picoprobe#74]
Hello, I am using as debug rp pico and target rp pico w.

Follow the connections as appendix a and the commands

-f interface/cmsis-dap.cfg -c "adapter speed 5000" -f target/rp2040.cfg -s tcl
i charge picoprobe.uf2 from here

any idea?
Thanks!

**Comment by crisgplj** [comment]
I use windows 10

**Comment by P33M** [comment]
Please ask support questions on the forum - https://forums.raspberrypi.com/viewforum.php?f=143
