### ISSUE TITLE
picoprobe - Interface 0 or 1 - zadig

### ISSUE THREAD

**Issue by NickDolfin** [raspberrypi/picoprobe#81]
I have a brand new Raspberry Pi Debug Probe (https://www.raspberrypi.com/products/debug-probe/)

I want to use it using visual studio code (https://arduino-pico.readthedocs.io/en/latest/platformio.html)

I find every where that I should use zadig to change the driver: "Remember that on Windows, you have to use [Zadig](https://zadig.akeo.ie/) to also load “WinUSB” drivers for the “Picoprobe (Interface 2)” device so that OpenOCD can speak to it."

(in https://arduino-pico.readthedocs.io/en/latest/platformio.html)

Using picoprobe.uf2:
I cannot find the Interface 2. Only 0 and 1:

![image](https://user-images.githubusercontent.com/121138495/230984600-ee1007fb-dea6-4ead-b157-fc24e1546f7f.png)
![image](https://user-images.githubusercontent.com/121138495/230984713-00d6fa55-c8c1-4ce0-9176-1082eac2bf22.png)

I also found two different uf2 files: picoprobe.uf2 and debugprobe.uf2 in the raspi github repositories. 
The usb ID is different than described here: https://wiki.freepascal.org/ARM_Embedded_Tutorial_-_Raspberry_Pi_Pico_Setting_up_for_Development

Using debugprobe.uf2:
![image](https://user-images.githubusercontent.com/121138495/230985955-1d86862f-e08e-46c8-9866-b20e146095a4.png)

I cannot get it to work.
Questions:
Which uf2 is do I have to use?
Is the USB ID correct?

Anyone any idea?

**Comment by P33M** [comment]
Those third-party instructions are incorrect. You do not need to use Zadig at all with the latest Picoprobe UF2.

Please follow the getting-started guide - https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf

**Comment by aallan** [comment]
See also https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html.

**Comment by NickDolfin** [comment]
I use platformio  - not the old fashioned arduino environment:
https://arduino-pico.readthedocs.io/en/latest/platformio.html

**Comment by aallan** [comment]
> I use platformio - not the old fashioned arduino environment: https://arduino-pico.readthedocs.io/en/latest/platformio.html

We officially support our own [C SDK](https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html), and [MicroPython](https://www.raspberrypi.com/documentation/microcontrollers/micropython.html). Unfortunately, we don't directly support either the Arduino environment or PlatformIO.

**Comment by NickDolfin** [comment]
Aha,

There are there two differerent uf2 files in your repository.
Whats the difference between picoprobe.uf2 and debugprobe.uf2?

I changed the drivers and flashed one of the two uf2 files into the Raspberry Pi Debug probe. I like to restore it to the original version.
Can you make a screenshot of the zadig program showing the correct windows 10 drivers? And which uf2 file is standard flashed in the debug probe?

**Comment by w4mmp-ron** [comment]
Hello,
As mentioned,  zadig is NOT used any longer for either Pico Probe or Debug Probe.   If you have the correct firmware loaded below is what windows will be display in the device manager.
![pico](https://user-images.githubusercontent.com/111645397/231337052-0dcc5163-d940-438d-972e-3a02d8081df9.png)

**Comment by NickDolfin** [comment]
Thanks, but that picture does not help.
Can someone answer the three questions in the previous post. Thanks.

**Comment by aallan** [comment]
> There are there two differerent uf2 files in your repository.
> Whats the difference between picoprobe.uf2 and debugprobe.uf2?

The picoprobe.uf2 firmware is intended to be run on a Raspberry Pi Pico (see Appendix A of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf), the debugprobe.uf2 firmware is intended to be run on a Raspberry Pi Debug Probe (see https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html).

> Can you make a screenshot of the zadig program showing the correct windows 10 drivers? And which uf2 file is standard flashed in the debug probe?

Zadig is no longer required under any circumstances. See the two links above for official instructions.

**Comment by NickDolfin** [comment]
Thanks,

I have changed the windows drivers using zadig. I want to restore them to the original, correct ones. Can you make a screenshot showing which drivers are correct?

**Comment by w4mmp-ron** [comment]
Using the Device Manager, delete those devices that you used zadig to install drivers for.  When the device manager asks if you want to delete the driver also, click that check box.   remove the Pico or the debug probe, (I have lost track of what you have) and reboot the PC.  Now plug in the Pico or debug probe.  The device manager should show what I had previously posted.

**Comment by NickDolfin** [comment]
Hi Ron,


I mentioned in the first sentence of the first post: 
I have a brand new Raspberry Pi Debug Probe (https://www.raspberrypi.com/products/debug-probe/)


I did what you wrote. This is what I get:
![image](https://user-images.githubusercontent.com/121138495/231571154-d22f8182-da72-4681-a191-85ecc0db81b3.png)

zooming in on one interfce:
![image](https://user-images.githubusercontent.com/121138495/231571368-203babbe-fd44-477e-ae34-579e3881d29d.png)

you can seen that a libusbK driver is installed for interface1
and

![image](https://user-images.githubusercontent.com/121138495/231571554-a516a33b-c10d-43a4-8ee4-9bb081694f5c.png)

for interface0 a libusb0 driver.

Windows does not have a default driver correctly installed after I changed things. It never will - thats windows. It remembers things based on the USB ID.

Can you show - just like I did - your installation settings with zadig.

**Comment by w4mmp-ron** [comment]
Well, if you insist that zadig is required, I can't help.  It has been mentioned several times in this issue, that zadig can not be used with the the most recent firmware for the debug probe.  
The debug probe works fine on my Windows 10 PC.  I simply attach it to the Windows 10 PC and Windows installs the correct driver automatically.

**Comment by NickDolfin** [comment]
I do not instist taht it is used. I just fucked up. So can you install zadig and show what your settings are?

**Comment by w4mmp-ron** [comment]
Forget about zadig!   See the below.   If this is what you see when the probe is attached,  delete it along with the driver if the device manager offers that option.
![pico](https://user-images.githubusercontent.com/111645397/231576115-bc975b87-d4a4-45ec-b8c4-d0708f6f764a.png)

**Comment by w4mmp-ron** [comment]
Also, set the device manager to show hidden devices.  Delete all the hidden devices if they are using any of the zadig drivers.
![pico-device](https://user-images.githubusercontent.com/111645397/231577248-8564fa75-9091-4132-9f6a-1f98b4f60464.png)

**Comment by NickDolfin** [comment]
For your and mine information:

Windows 10 is really a pain in the ass.
I ended up rstoring it from a backup that I made a few days ago (always a good idea to have backups).
The Raspberry Pi Debug Probe installed in an USB3 socket:

![image](https://user-images.githubusercontent.com/121138495/231899592-29f57c7b-f2bf-4052-bed6-c98abb68dc23.png)
![image](https://user-images.githubusercontent.com/121138495/231900330-55bee96f-2fb4-4cc5-82db-05ddea8bbbbc.png)
![image](https://user-images.githubusercontent.com/121138495/231900621-62c52f05-0b1e-49c9-8727-d73a495f6129.png)



![image](https://user-images.githubusercontent.com/121138495/231899754-d967a439-69e4-49c7-9464-e7294baca191.png)
![image](https://user-images.githubusercontent.com/121138495/231899813-51bf6396-2464-4e0e-80ca-2896e5d91ce6.png)
![image](https://user-images.githubusercontent.com/121138495/231899846-9dbd9295-279b-4567-9d97-5f92d296b1a3.png)

**Comment by Thomas-Mcilwraith** [comment]
Hi there, 
I am currently having the same issue - is the previous post from [NickDolfin](https://github.com/NickDolfin) the correct configuration? that is exaclty what i have in my Zadig display (although newer versions now)
