### ISSUE TITLE
why the newest FM can't detect the MCU?

### ISSUE THREAD

**Issue by MrsKan** [raspberrypi/picoprobe#82]
I clone the project and build the source code, got a .uf2 file, and I download it to the pico. when I use openocd to connect the picoprobe, it shows DAP init fail and the LED on the pico didn't light or shine. But the newest released .uf2 file can connected. any wrong did I made? It confused me.
![image](https://user-images.githubusercontent.com/38273703/235478898-3d0d1ddb-4a80-4178-9bea-9dac59126b56.png)

**Comment by P33M** [comment]
This is probably because I merged the debugprobe branch without reverting the board include to picoprobe. What happens if you swap the header file included here? https://github.com/raspberrypi/picoprobe/blob/master/src/picoprobe_config.h#L50

**Comment by MrsKan** [comment]
thanks for update, it is great.
